name: Automate PR Management

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  add_pr_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: ./tools/addPr2Project.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PR_ASSEMBLE }}
